### ISSUE TITLE
Support for Typescript?

### ISSUE THREAD

**Issue by theshumanator** [jeremydaly/lambda-api#110]
Hi, do you have a sample typescript which uses lambda-api?
I'm getting a bunch of errors and just want to make sure I'm not missing anything.

The errors I am getting are like this:

```
node_modules/lambda-api/index.d.ts:152:3 - error TS7010: 'getLink', which lacks return-type annotation, implicitly has an 'any' return type.

152   getLink(s3Path: string, expires?: number, callback?: (err, data) => void);
      ~~~~~~~

```
Thanks

**Comment by stawecki** [comment]
Try using the updated type declarations from maxmellen's PR: https://github.com/maxmellen/lambda-api/tree/strict-ts

My sample `handler.ts` looks like this (note that it's not ideal, because i'm still using require and assigning it the API type, but it works. Can't seem to use import to retrieve createAPI in one go.).

```typescript
import { API } from "lambda-api";
const api = require("lambda-api")() as API;

api.get("/status", async (req, res) => {
  return { status: 'ok' }
});

exports.run = async (event: any, context: any) => {
  return await api.run(event, context)
}
```

Any other ideas appreciated.

**Comment by stawecki** [comment]
Just to elaborate the import issue, the suggested import:
```typescript
import API from 'lambda-api'
const api = API({});
```
Transpiles into:
```javascript
const lambda_api_1 = require("lambda-api");
const api = lambda_api_1.default({});
```
Which results in: `TypeError: lambda_api_1.default is not a function`
I believe it's the correct behaviour for `export default createAPI;` in *index.d.ts*, but it doesn't match the `module.exports = opts => new API(opts)` in *index.js*. The fix is to add the following line to *index.js*:
```javascript
module.exports.default = opts => new API(opts)
```
I didn't start a PR for this, because it may not be the ideal solution. I also may be initialising the API wrong.

**Comment by jsepia** [comment]
This worked for me:

**handler.ts**

```ts
import API from 'lambda-api'
import usersApi from './api/users'
import { APIGatewayProxyHandler, APIGatewayEvent, APIGatewayProxyCallback, Context } from 'aws-lambda';

const api = API({ version: 'v0.1.0', base: 'v0' })

api.get('/users', usersApi)

const handler: APIGatewayProxyHandler = (event: APIGatewayEvent, context: Context, callback: APIGatewayProxyCallback) => {
  api.run(event, context, callback)
}

export { handler }
```

**Comment by stawecki** [comment]
@jsepia what are your `compilerOptions` in **tsconfig.json**, if I may know?

**Comment by stawecki** [comment]
Looking at [ts-lambda-api](https://github.com/djfdyuruiry/ts-lambda-api), looks like you need `"esModuleInterop": true` in **tsconfig.json**'s `compilerOptions`, [unless you're using Babel](https://itnext.io/great-import-schism-typescript-confusion-around-imports-explained-d512fc6769c2).

I've tested this myself now and it works.

@jeremydaly can we add this information to the README?

I also think it might be worth adding the `module.exports.default` mapping as `esModuleInterop` is [not enabled by default in the TS compiler](https://www.typescriptlang.org/docs/handbook/compiler-options.html) and it shouldn't affect Babel or ES6+ users.
