### ISSUE TITLE
It has dependencies.

### ISSUE THREAD

**Issue by schulke-214** [jeremydaly/lambda-api#116]
`/lib/request.js`
```
const QS = require('querystring');
```

This looks like a dependency - im noting this since you're advertising this framework as 0 dependency framework.

**Comment by schulke-214** [comment]
Another Example:

`/lib/s3-service.js`
```
const AWS = require('aws-sdk');
```

**Comment by jeremydaly** [comment]
Hi @schulke-214,

The `querystring` package is included in Node.js core, so you don't need to include or require any third-party modules. This is not a dependency, just a way to access a feature of Node.js.

The `aws-sdk` requirement is technically a dependency, yes. But since the `aws-sdk` is preinstalled in the Lambda runtime, you do not need to include the module as a "dependency" in your `package.json` when you package your deployment artifacts. Therefore, using the `aws-sdk` doesn't add any additional dependencies to your functions.

Hope that clarifies things.

- Jeremy
