### ISSUE TITLE
Is it possible to implement mtls?

### ISSUE THREAD

**Issue by glauberalmeida** [jeremydaly/lambda-api#218]
How to configure certificates for mTLS connection in LambdaAPI?

**Comment by naorpeled** [comment]
First of all, sorry for the huge delay.

We currently don't have any utils that would really help with implementing this,
will give this some thought though because it would be very helpful.

I recommend taking a look at [this repo](https://github.com/aws-samples/serverless-mutual-tls),  although it's implemented with Java, it should give a general overview on how to do so.

I'll be closing this issue but feel free to ping me if you have any further questions.

**Comment by glauberalmeida** [comment]
Would it be possible to include this implementation in the roadmap?
