### ISSUE TITLE
Add additional logging support

### ISSUE THREAD

**Issue by jeremydaly** [jeremydaly/lambda-api#45]
Provide a logging mechanism to help developers control logging through logging levels as well as provide additional context information about each log entry.

It should support (at a minimum): info, error, debug, fatal, warn

Logs should be in JSON format and contain timestamp, route info, etc.

**Comment by jeremydaly** [comment]
To clarity, AWS Lambda has built in (fairly efficient) logging. Developers can certainly implement their own logging, but having it write a standard format with additional internals about the route executed would be helpful (IMO). 

The format should be configurable, probably through a transformation object.

**Comment by psteger** [comment]
So I know we touched on this a bit but it was several weeks ago now and regardless I'd like to get info down in writing.

1) Is your idea something along the lines of Fastify where it implements different log levels with a logger object during instantiation? Basically, if someone instantiates Lambda-API with {logger: true} it defaults to using console.log(...) but if they specify {logger: {level: info}} it uses console.info(...) behind the scenes?

2) The configurable object I'm guessing would also be a part of the logger object passed in. I'm imagining {logger: {format: {time: true, routeInfo: false}}} (though I think time is a bad option since it's redundant in CloudWatch). It would default to a certain format but I'm unsure without experimenting what that format should be.

**Comment by jeremydaly** [comment]
@psteger, yes, my intention was to follow something similar to Fastify. They attach a `log` property to their `request` object and then allow you to set a level after that, e.g. `request.log.info`. They use Pino behind the scenes, but since we are logging with Lambda, there is no need for any additional dependencies.

I like the idea of following the log levels and priorities of Pino: https://github.com/pinojs/pino/blob/master/docs/API.md#level. I think that makes sense, and there certainly could be ways in the future to either override the logger, or make the code portable if you wanted it to run in containers or some other environment.

Although a timestamp is redundant, I think it still makes sense so that the JSON for the log is completely compartmentalized. If another service was ingesting it, it would need to look at the rest of the envelope to get the time.

The "standard" format is something we should iterate on. Rather than your suggestion in point 2 above (`{logger: {format: {time: true, routeInfo: false}}}`), I think it would make more sense to use a transformation object instead. That way the logger object could be seeded with `request`, `response`, `context`, etc. This would allow you to define a custom log format like this:

```javascript
{
  logger: {
    level: 'warn',
    format: {
      timestamp: Date.now(),
      id: context.awsRequestId,
      route: req.route,
      method: req.method,
      returnedStatus: res._statusCode
      ....
   }
}
```

Thoughts?
