### ISSUE TITLE
Type script issue class variables are not accesible

### ISSUE THREAD

**Issue by harshit-yadav** [jeremydaly/lambda-api#79]
> This is my Handler code:

```
const config = new Config();
const logger = new Logger({name: "foo-endpoints", level: "trace"});
const addfoo = new Addfoo(logger, config);


const api = API({
  base: "v1",
  version: "v1.0",
  logger: true
});

api.post('/foo', addfoo.handle);


// Declare Lambda handler
exports.handler = (event, context) => {
  // Run the request
  return api.run(event, context)
}
```

> And this is Addfoo code

```
export class Addfoo {
  public logger: Logger;
  public config: Config;

  constructor(
    logger: Logger, config: Config
 
  ) {
    this.logger  = logger.child("Addfoo.ts");
    this.config  = config;
  }

  public handle(req: Request, res: Response): Promise<any> {
    try {
      this.logger.log("req",req)
      res.status(200).json({a:1})
    } catch (e) {
      return res.error(e)
    }
  }
}

```
this.logger is accessible in constructor but this.logger is not accessible in handle function. And if i am trying to declare any other dependency same issue is accruing with those dependencies. 

Serverless: [500] {"headers":{"content-type":"application/json"},"statusCode":500,"body":"{\"error\":\"this.logger.log is not a function\"}","isBase64Encoded":false}

**Comment by jeremydaly** [comment]
Hi @harshit-yadav,

It appears that the logger isn't accessible because you're only passing a reference to the `handle` function into the API route. You could accomplish this by using [namespaces](https://github.com/jeremydaly/lambda-api#namespaces) to store a reference to your `Logger` object which would then be accessible from the `request` object.
