### ISSUE TITLE
Allow route handler function to have an arity less than 2

### ISSUE THREAD

**Issue by mjdickinson** [jeremydaly/lambda-api#93]
Route middleware functions are checked for having arity of 3, i.e.:
```
middleware(req, res, next)
```

This seems reasonable since middleware is expected to call `next()`, so needs all three arguments.

However, the final handler function in a route declaration is currently forced to have an arity of 2, i.e.:
```
handler(req, res)
```

Since handlers can return a response body instead of calling `res.send()`, it is quite possible that the second argument is not used.  Indeed, even the `req` argument may not be used in many cases.

Can the check on route handler function be changed to allow any arity less than 3, so I am not be forced to declare unused arguments?

E.g.  I want to be able to declare a route like this:
```
api.get('/users', async () => {
	const users = await getAllUsers();
	return users.map( ... );
);
```

**Comment by jeremydaly** [comment]
This makes sense. Adding to the roadmap.

**Comment by hassankhan** [comment]
Just wanted to follow up, @mjdickinson are you using TypeScript by any chance? The commit fixing this changed the types in a way that requires users to check for the existence of `req` and `res` before using them. The optional parameters should be reverted to how they were before, since TypeScript doesn't force declaring unused arguments (see [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25385) for more details).

@jeremydaly would you be open to a PR reverting the type changes?
